spring:
  application:
    name: app
  profiles:
    active: dev
app:
  jwt:
    secret: ${{ secrets.JWT_SECRET }}
    expiration: 3600000
  admin:
    email: ${{ secrets.ADMIN_EMAIL }}
    password: ${{ secrets.ADMIN_PASSWORD }}
